name: NPM Publish

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to publish (beta, latest, etc.)"
        required: false
        default: "latest"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install dependencies
        run: |
          forge install
          npm ci

      - name: Build contracts
        run: forge build

      - name: Format code
        run: forge fmt

      - name: Run tests
        run: forge test

      - name: Build TypeScript
        run: npm run build:npm

      - name: Publish to NPM
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            npm publish --tag ${{ github.event.inputs.tag }}
          else
            npm publish
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub release summary
        run: |
          echo "## 📦 NPM Package Published" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Package: \`@lotus-research/reflex\`" >> $GITHUB_STEP_SUMMARY
          echo "Version: \`$(node -p "require('./package.json').version")\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Install" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
          echo "npm install @lotus-research/reflex" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
