name: Pre-publish Check

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install dependencies
        run: |
          forge install
          npm ci

      - name: Build contracts
        run: forge build

      - name: Run tests
        run: forge test

      - name: Check TypeScript compilation
        run: npm run build:npm

      - name: Verify package can be built
        run: npm pack --dry-run

      - name: Check package contents
        run: |
          echo "## 📦 Package Contents Check" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          npm pack --dry-run 2>&1 | head -20 >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
